name: recorder_in_background
description: A Flutter example using Maps SDK for Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  magiclane_maps_flutter: ^3.1.3

  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
